const FACULTY_CATEGORIES = ['LIVE_CLASS', 'RECORDING', 'TEST', 'PDF'];

const BATCH_STATUSES = [
  'ACTIVE',
  'UPCOMING',
  'INACTIVE',
  'COMPLETED',
  'ARCHIVED',
  'CANCELLED'
];

const FEE_CURRENCIES = ['INR', 'USD', 'EUR'];

module.exports = {
  FACULTY_CATEGORIES,
  BATCH_STATUSES,
  FEE_CURRENCIES
};
