const {
  CURRENT_AFFAIR_CATEGORIES: CATEGORIES,
  CURRENT_AFFAIR_CATEGORY_LIST: CATEGORY_LIST,
  PDF_REQUIRED_CATEGORIES,
  YEAR_MONTH_REQUIRED_CATEGORIES,
  MONTHS,
  YEAR_OPTIONS
} = require('./currentAffairEnums');

const CLOUDINARY_FOLDER = 'current-affairs';
const MAX_PDF_SIZE_BYTES = 10 * 1024 * 1024;

module.exports = {
  CATEGORIES,
  CATEGORY_LIST,
  PDF_REQUIRED_CATEGORIES,
  YEAR_MONTH_REQUIRED_CATEGORIES,
  MONTHS,
  YEAR_OPTIONS,
  CLOUDINARY_FOLDER,
  MAX_PDF_SIZE_BYTES
};
