const {
  MAINS_CATEGORY_LIST: MAINS_CATEGORIES,
  CORRECT_ANSWER_OPTIONS,
  BULK_TEMPLATE_HEADERS
} = require('./currentAffairEnums');

const BULK_MAX_FILE_SIZE_BYTES = 15 * 1024 * 1024;
const QUESTION_IMAGE_MAX_BYTES = 5 * 1024 * 1024;

module.exports = {
  MAINS_CATEGORIES,
  CORRECT_ANSWER_OPTIONS,
  BULK_TEMPLATE_HEADERS,
  BULK_MAX_FILE_SIZE_BYTES,
  QUESTION_IMAGE_MAX_BYTES
};
