const PAYMENT_STATUSES = ['PAID', 'PENDING', 'PARTIAL', 'OVERDUE'];

const ENROLLMENT_STATUSES = ['ACTIVE', 'INACTIVE'];

const ACADEMIC_STUDENT_STATUSES = ['ACTIVE', 'INACTIVE'];

module.exports = {
  PAYMENT_STATUSES,
  ENROLLMENT_STATUSES,
  ACADEMIC_STUDENT_STATUSES
};
