const MODULE_TYPES = {
  CURRENT_AFFAIRS: 'CURRENT_AFFAIRS',
  FREE_RESOURCES: 'FREE_RESOURCES'
};

const RESOURCE_TYPES = ['PDF', 'ARTICLE', 'MAGAZINE', 'INFOGRAPHIC', 'VIDEO'];

const FILTER_TYPES = {
  SUBJECT: 'SUBJECT',
  CLASS: 'CLASS',
  PAPER: 'PAPER',
  YEAR: 'YEAR',
  MONTH: 'MONTH',
  CURRENT_AFFAIRS_TYPE: 'CURRENT_AFFAIRS_TYPE'
};

const CATEGORY_NAME_HINTS = {
  NCERT: 'ncert',
  PYQ: ['previous year', 'pyq'],
  STUDY_MATERIAL: 'study material',
  MOCK_TEST: ['mock test', 'mock tests', 'free mock']
};

const FREE_RESOURCE_FILTER_KEYS = {
  NCERT: ['SUBJECT', 'CLASS'],
  PYQ: ['SUB_CATEGORY', 'PAPER', 'YEAR'],
  STUDY_MATERIAL: ['SUB_CATEGORY'],
  MOCK_TEST: ['SUB_CATEGORY'],
  GENERIC: ['SUBJECT', 'CLASS']
};

module.exports = {
  MODULE_TYPES,
  RESOURCE_TYPES,
  FILTER_TYPES,
  CATEGORY_NAME_HINTS,
  FREE_RESOURCE_FILTER_KEYS
};
